services:
  bot:
    build: .
    environment:
      BOT_TOKEN: '${BOT_TOKEN}'
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DATABASE}'
    volumes:
      - botlogs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: '${POSTGRES_DATABASE}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -d ${POSTGRES_DATABASE} -U ${POSTGRES_USER} || exit 1'
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backup:
    image: devp1337/backup:2.0.0
    environment:
      PROVISION_MODE: postgres
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DATABASE: '${POSTGRES_DATABASE}'
      POSTGRES_HOST: db
      RESTIC_REPOSITORY_NAME: '${RESTIC_REPOSITORY_NAME}'
      RESTIC_PASSWORD: '${RESTIC_PASSWORD}'
      TELEGRAM_TOKEN: '${BOT_TOKEN}'
      TELEGRAM_CHAT_ID: '${TELEGRAM_CHAT_ID}'
      TELEGRAM_COMMENT: '${TELEGRAM_COMMENT}'
      CRON: '${CRON}'
      TARGET_DOMAIN: '${TARGET_DOMAIN}'
      TARGET_DOMAIN_USER: '${TARGET_DOMAIN_USER}'
      SSH_PRIVATE_KEY_BASE64: '${SSH_PRIVATE_KEY_BASE64}'
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -h db > /dev/null || exit 1'
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  pgdata:
  botlogs:
